# App
spring.application.name=FFB_be

#Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Security & API Keys
API_KEY=${API_KEY}
SECRET_KEY=${SECRET_KEY}
jwt.secret=${JWT_SECRET}

# Microservices
rcm_url=https://recommendation-api-318865989290.asia-southeast1.run.app

# Cloudinary
cloud_name=${CLOUD_NAME}
api_key=${CLOUD_API_KEY}
api_secret=${CLOUD_API_SECRET}

# AES
aes.secret.key=${AES_SECRET_KEY}

# VietQR
vietqr.client-id=${VIETQR_CLIENT_ID}
vietqr.api-key=${VIETQR_API_KEY}

# Mapbox
mapbox.api.key=${MAPBOX_API_KEY}

# SMS
API_URL=${API_URL}

# BankAccount
accountNumber=${account_number}
bankCode=${bank_code}